#ifndef LINEAR_FORM_ERRORS_H
#define LINEAR_FORM_ERRORS_H

typedef enum {
    LINEAR_FORM_OPERATION_OK = 0,
    MEMORY_ALLOCATION_FAILED = 1,
    INCOMPATIBLE_LINEAR_FORM_TYPES = 2,
    LINEAR_FORM_NOT_DEFINED = 3,
    OPERATION_NOT_DEFINED = 4,
    NEGATIVE_QUANTITY = 5,
    INDEX_OUT_OF_BOUNDS = 6,
    RESULT_LENGHT_IS_INCORRECT = 7
} LinearFormErrors;

#endif